#github resource
publishDir = "public"

# Site settings
baseURL = "https://f19.pl/"
languageCode = "en-us"
title = "Fabryczna 19 w Legnicy"
theme = "forty"

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Grzegorz Świerniak"
  description = "Legnica - ul. Fabryczna 19"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = "front_low.jpg"

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "DW-House"
    subtitle = "Mieszkania dla Ciebie i Twojej rodziny"
    menu = "Menu"
    logo = "logo.png"

    [[params.navigation.links]]
      name = "O inwestycji"
      url = "o_inwestycji_mieszkania_sprzedaz_legnica.html"

    [[params.navigation.links]]
      name = "Galeria"
      url = "galeria_mieszkania_sprzedaz_legnica.html"

     [[params.navigation.links]]
      name = "Mieszkania"
      url = "mieszkania_mieszkania_sprzedaz_legnica.html"

     [[params.navigation.links]]
      name = "Lokalizacja"
      url = "lokalizacja_mieszkania_sprzedaz_legnica.html"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    #[[params.navigation.button1]]
    #  name = "Get Started"
    #  url = "blogs"

    # Button Style 2
    #[[params.navigation.button2]]
    #  name = "Log In"
    #  url = "#"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Nowa inwestycja w centrum Legnicy"
    subtitle = "Komfortowe mieszkania dla Ciebie i Twojej rodziny"
    buttonText = "Dalej"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "O inwestycji"
      subtitle = "Dlaczego warto tu mieszkać"
      image = "1 — 300 KB.jpg"
      url = "o_inwestycji_mieszkania_sprzedaz_legnica.html"

    [[params.tiles.showcase]]
      title = "Galeria"
      subtitle = "Wizualizacje oraz zdjęcia budowy"
      image = "parter.png"
      url = "galeria_mieszkania_sprzedaz_legnica.html"

    [[params.tiles.showcase]]
      title = "Mieszkania"
      subtitle = "Zobacz listę dostępnych lokali"
      image = "lista_lokali.png"
      url = "mieszkania_mieszkania_sprzedaz_legnica.html"

    [[params.tiles.showcase]]
      title = "Lokalizacja"
      subtitle = "Poznaj zalety mieszkania w centrum Legnicy"
      image = "google_maps.jpeg"
      url = "lokalizacja_mieszkania_sprzedaz_legnica.html"

    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "O nas"
    subtitle = "Jesteśmy nowoczesną firmą deweloperską, która ceni sobie jakość oraz terminowość. Przede wszystkim stawiamy na inwestycje zlokalizowane w centrach miast, które mają łatwy dostęp do wszelkich udogodnień miasta takich jak komunikacja miejska, sklepy, przedszkola czy szkoły. Stawiamy również na nowoczesny design naszych inwestycji, tak aby naszym klienom mieszkało się komfortowo, bezpiecznie oraz funkcjonalnie."


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Wyślij"
    buttonClear = "Wyszyść"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    formEmail = "f/mkgnlnwa"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "biuro@dw-house.pl"

    [[params.contact.phone]]
    title = "Sprzedaż"
    phone = "(+48) 731 121 888"

    [[params.contact.phone2]]
    title2 = "Biuro"
    phone2 = "(+48) 782 337 751"

    [[params.contact.address]]
    title = "DWH Invest Sp. z o.o."
    street = "ul. Św. Marcin 29/8"
    city = "61-806 Poznań"
    country = "NIP 739-390-63-90"

  # Footer section
  [params.footer]
    enable = true
    copyright = "DWH Invest Sp. z o.o."

    # Uses font awesome icons
    [[params.footer.social]]
      icon = "fa-facebook"
      url= "https://www.facebook.com/profile.php?id=61569606495394"
      label = "Facebook"

    

